sonar.projectKey=leguia-cotizador-android
sonar.projectName=Cotizador Leguia Android
sonar.sources=app/src/main
sonar.tests=app/src/test
sonar.sourceEncoding=UTF-8
sonar.java.binaries=app/build/tmp/kotlin-classes/debug
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/testDebugUnitTestCoverage/testDebugUnitTestCoverage.xml
